//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibraryDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sales
    {
        public int idSale { get; set; }
        public System.DateTime Sale_Date { get; set; }
        public Nullable<int> idCustomer { get; set; }
        public Nullable<int> idProduct { get; set; }
        public Nullable<int> Count { get; set; }
        public Nullable<decimal> Price_Total { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual Product Product { get; set; }
    }
}
