//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibraryDBComputers
{
    using System;
    using System.Collections.Generic;
    
    public partial class Auth
    {
        public string Login { get; set; }
        public string Password { get; set; }
        public int idRole { get; set; }
        public int idAuth { get; set; }
    
        public virtual Roles Roles { get; set; }
    }
}
